#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <signal.h> // Required for handling SIGPIPE
#include <pthread.h>

#include "authorization.h"
#include "sensor_manager.h"
#include "protocol.h"

#define PORT 8080
#define MAX_CONCURRENT_SESSIONS 32

// Paths to certificates generated by quick_start.sh
#define SERVER_CERT "certs/server.crt"
#define SERVER_KEY  "certs/server.key"
#define CA_CERT     "certs/ca.crt"

typedef struct {
    int client_fd;
    SSL_CTX *ssl_ctx;
    SensorManager *sensor_mgr;
    struct sockaddr_in client_addr;
} ClientSession;

static pthread_mutex_t session_mutex = PTHREAD_MUTEX_INITIALIZER;
static int current_sessions = 0;
static int max_observed_sessions = 0;

void init_openssl();
void cleanup_openssl();
void *client_session_thread(void *arg);

int try_reserve_session_slot() {
    int accepted = 0;

    pthread_mutex_lock(&session_mutex);
    if (current_sessions < MAX_CONCURRENT_SESSIONS) {
        current_sessions++;
        if (current_sessions > max_observed_sessions)
            max_observed_sessions = current_sessions;
        accepted = 1;
    }

    printf("[SESSIONS] Current: %d | Max Observed: %d | Limit: %d\n",
           current_sessions, max_observed_sessions, MAX_CONCURRENT_SESSIONS);
    pthread_mutex_unlock(&session_mutex);

    return accepted;
}

void release_session_slot() {
    pthread_mutex_lock(&session_mutex);
    if (current_sessions > 0)
        current_sessions--;

    printf("[SESSIONS] Current: %d | Max Observed: %d | Limit: %d\n",
           current_sessions, max_observed_sessions, MAX_CONCURRENT_SESSIONS);
    pthread_mutex_unlock(&session_mutex);
}

// ============================================================
// Helper: Initialize OpenSSL Context
// ============================================================
SSL_CTX* create_context() {
    const SSL_METHOD *method = TLS_server_method();
    SSL_CTX *ctx = SSL_CTX_new(method);
    if (!ctx) {
        perror("[ERROR] Unable to create SSL context");
        ERR_print_errors_fp(stderr);
        exit(EXIT_FAILURE);
    }
    return ctx;
}

// ============================================================
// Helper: Configure Certificates for mTLS
// ============================================================
void configure_context(SSL_CTX *ctx) {
    if (SSL_CTX_use_certificate_file(ctx, SERVER_CERT, SSL_FILETYPE_PEM) <= 0) {
        ERR_print_errors_fp(stderr);
        exit(EXIT_FAILURE);
    }

    if (SSL_CTX_use_PrivateKey_file(ctx, SERVER_KEY, SSL_FILETYPE_PEM) <= 0) {
        ERR_print_errors_fp(stderr);
        exit(EXIT_FAILURE);
    }

    if (!SSL_CTX_load_verify_locations(ctx, CA_CERT, NULL)) {
        ERR_print_errors_fp(stderr);
        exit(EXIT_FAILURE);
    }

    // Force Client Authentication (mTLS)
    SSL_CTX_set_verify(ctx, SSL_VERIFY_PEER | SSL_VERIFY_FAIL_IF_NO_PEER_CERT, NULL);
}

// ============================================================
// Helper: Create Listening Socket
// ============================================================
int create_socket(int port) {
    int s;
    struct sockaddr_in addr;

    addr.sin_family = AF_INET;
    addr.sin_port = htons(port);
    addr.sin_addr.s_addr = htonl(INADDR_ANY);

    s = socket(AF_INET, SOCK_STREAM, 0);
    if (s < 0) {
        perror("[ERROR] Unable to create socket");
        exit(EXIT_FAILURE);
    }

    // Allow immediate port reuse on restart
    int opt = 1;
    setsockopt(s, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));

    if (bind(s, (struct sockaddr*)&addr, sizeof(addr)) < 0) {
        perror("[ERROR] Unable to bind");
        exit(EXIT_FAILURE);
    }

    if (listen(s, 5) < 0) {
        perror("[ERROR] Unable to listen");
        exit(EXIT_FAILURE);
    }

    return s;
}

void *client_session_thread(void *arg) {
    ClientSession *session = (ClientSession *)arg;
    ClientIdentity id;
    char ip_buf[INET_ADDRSTRLEN] = {0};

    inet_ntop(AF_INET, &session->client_addr.sin_addr, ip_buf, sizeof(ip_buf));
    printf("[CONN] Worker thread started for client %s\n", ip_buf);

    SSL *ssl = SSL_new(session->ssl_ctx);
    if (!ssl) {
        fprintf(stderr, "[ERROR] Failed to allocate SSL object for %s\n", ip_buf);
        close(session->client_fd);
        free(session);
        return NULL;
    }

    SSL_set_fd(ssl, session->client_fd);

    if (SSL_accept(ssl) <= 0) {
        printf("[AUTH] TLS Handshake failed. Rejecting connection from %s.\n", ip_buf);
        ERR_print_errors_fp(stderr);
    } else {
        if (authorize_client(ssl, &id) == 0) {
            if (id.role != ROLE_UNAUTHORIZED) {
                printf("[AUTH] Access GRANTED to User: '%s' | Assigned Role: '%s'\n", id.common_name, role_to_string(id.role));

                ProtocolContext protocol_ctx;
                protocol_init(&protocol_ctx, ssl, id, session->sensor_mgr);
                protocol_run(&protocol_ctx);

                printf("[CONN] Session ended for %s\n", id.common_name);
            } else {
                printf("[AUTH] Access DENIED: Client '%s' has an unauthorized role.\n", id.common_name);
            }
        } else {
            printf("[AUTH] Access DENIED: Missing or invalid client certificate from %s.\n", ip_buf);
        }
    }

    printf("[CONN] Cleaning up session and closing socket for %s...\n", ip_buf);
    SSL_shutdown(ssl);
    SSL_free(ssl);
    close(session->client_fd);
    free(session);
    release_session_slot();
    printf("[CONN] Session fully closed for %s.\n", ip_buf);

    return NULL;
}

// ============================================================
// MAIN SERVER ENTRY
// ============================================================
int main() {
    int sock;
    SSL_CTX *ctx;
    SensorManager sensor_mgr;

    // IMPORTANT: Ignore SIGPIPE to prevent server crashes on client disconnects
    signal(SIGPIPE, SIG_IGN);

    printf("====================================================\n");
    printf("   Starting Sentinel-RT Monitoring System (Server)  \n");
    printf("====================================================\n");
    
    // 1. Initialize Hardware & Background Polling Threads
    if (manager_init(&sensor_mgr) != 0) {
        fprintf(stderr, "[FATAL] Failed to initialize hardware/sensor manager\n");
        return 1;
    }
    printf("[SYSTEM] Hardware threads actively polling (Vib:17, Snd:27, Temp:4, Cur:I2C)\n");

    // 2. Initialize Security
    init_openssl(); 
    ctx = create_context();
    configure_context(ctx);

    // 3. Prepare Network
    sock = create_socket(PORT);

    

    // 4. Infinite Listener Loop
    while (1) {
        printf("\n[NETWORK] Ready and waiting for a new client connection on port %d...\n", PORT);
        
        struct sockaddr_in addr;
        unsigned int len = sizeof(addr);
        
        // Server blocks here until a client connects
        int client_fd = accept(sock, (struct sockaddr*)&addr, &len);

        if (client_fd < 0) {
            perror("[ERROR] Accept failed");
            continue; // Do not exit, go back to waiting
        }

        char ip_buf[INET_ADDRSTRLEN] = {0};
        inet_ntop(AF_INET, &addr.sin_addr, ip_buf, sizeof(ip_buf));
        printf("[CONN] TCP Connection established from IP: %s\n", ip_buf);

        if (!try_reserve_session_slot()) {
            printf("[SESSIONS] Connection rejected for %s: session limit reached (%d).\n",
                   ip_buf, MAX_CONCURRENT_SESSIONS);
            close(client_fd);
            continue;
        }

        ClientSession *session = (ClientSession *)malloc(sizeof(ClientSession));
        if (!session) {
            fprintf(stderr, "[ERROR] Failed to allocate client session state\n");
            close(client_fd);
            release_session_slot();
            continue;
        }

        session->client_fd = client_fd;
        session->ssl_ctx = ctx;
        session->sensor_mgr = &sensor_mgr;
        session->client_addr = addr;

        pthread_t thread_id;
        if (pthread_create(&thread_id, NULL, client_session_thread, session) != 0) {
            perror("[ERROR] Failed to create client worker thread");
            close(client_fd);
            free(session);
            release_session_slot();
            continue;
        }

        // Detached workers self-clean when a client disconnects.
        pthread_detach(thread_id);
    }

    // 8. Server Cleanup (Unreachable in standard operation due to while(1))
    close(sock);
    SSL_CTX_free(ctx);
    cleanup_openssl(); 
    manager_cleanup(&sensor_mgr);
    return 0;
}

void init_openssl() { 
    SSL_load_error_strings();   
    OpenSSL_add_ssl_algorithms();
}

void cleanup_openssl() {
    EVP_cleanup();
}
